apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab-observability
  name: frontend
  labels:
    name: frontend
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 'romuloslv/frontend:1.0'
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
              cpu: 250m
          env:
            - name: COUNTER_ENDPOINT
              value: 'http://backend:5000'
          ports:
            - name: frontend-port
              containerPort: 8000
              protocol: TCP