apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: lab-app
  name: igrs-develop
  labels:
    app: simpleapp
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webproxy-ingress-simpleapp
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: webproxy-ingress-simpleapp
                port:
                  number: 80
          - path: /code
            pathType: Prefix
            backend:
              service:
                name: webproxy-ingress-simpleapp
                port:
                  number: 80