apiVersion: v1
kind: Service
metadata:
  namespace: lab-app
  name: webproxy-ingress-simpleapp
  labels:
    app: simpleapp
spec:
  type: ClusterIP
  selector:
    app: simpleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8008