apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab-app
  name: simpleapp
  labels:
    app: simpleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
        - name: simpleapp
          image: '${docker_image}'
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
              cpu: 250m
          ports:
            - containerPort: 8008
          envFrom:
            - configMapRef:
                name: cfgm-develop