apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab-observability
  name: backend
  labels:
    name: backend
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: '${docker_image}'
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
              cpu: 250m
          ports:
            - name: backend-port
              containerPort: 5000
              protocol: TCP